//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities1 : DbContext
    {
        public DbCvEntities1()
            : base("name=DbCvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblAbout> TblAbout { get; set; }
        public DbSet<TblAdmin> TblAdmin { get; set; }
        public DbSet<TblCertificate> TblCertificate { get; set; }
        public DbSet<TblCommunication> TblCommunication { get; set; }
        public DbSet<TblEducation> TblEducation { get; set; }
        public DbSet<TblExperience> TblExperience { get; set; }
        public DbSet<TblHobby> TblHobby { get; set; }
        public DbSet<TblSkill> TblSkill { get; set; }
        public DbSet<TblSocialMedia> TblSocialMedia { get; set; }
    }
}
