//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subheading1 { get; set; }
        public string Subheading2 { get; set; }
        public string GPA { get; set; }
        public string Date { get; set; }
    }
}
